
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sutanto dwi putra - 22110233 kelas L-2022
 */

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Penjualan_sutantodwiputra extends javax.swing.JFrame {
    Connection c;
    ResultSet r;
    Statement s;
    PreparedStatement ps;
    DefaultTableModel tabel1;
    /**
     * Creates new form Penjualan_sutantodwiputra
     */
    public Penjualan_sutantodwiputra() {
        initComponents();
//      Color co=new Color(42,147,213);
        Color co=new Color(18,84,136);
        getContentPane().setBackground(co);
        getKoneksi();
        setTabel1();
        tampil_data1();
        String kodeRandom = generateRandomCode();
        String transactionId = "TRS0" + kodeRandom;
        IdTrs_sutantodwiputra.setText(transactionId);
        KdBrg_sutantodwiputra.setSelectedItem("");
        NamaBrg_sutantodwiputra.setText("");
        HargaBrg_sutantodwiputra.setText("");
        JmlBeli_sutantodwiputra.setText("");
        JmlBayar_sutantodwiputra.setText("");
        Diskon_sutantodwiputra.setText("");
        TotalByr_sutantodwiputra.setText("");
        jLabel1.setForeground(Color.white);
        jLabel2.setForeground(Color.white);
        jLabel3.setForeground(Color.white);
        jLabel4.setForeground(Color.white);
        jLabel5.setForeground(Color.white);
        jLabel6.setForeground(Color.white);
        jLabel7.setForeground(Color.white);
        jLabel8.setForeground(Color.white);
        jLabel9.setForeground(Color.white);
        jLabel10.setForeground(Color.white);
        jLabel11.setForeground(Color.white);
//        btnBaru_sutantodwiputra.setForeground(Color.white);
    }

        private void getKoneksi() {
        if(c==null){
        try {
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/DBPENJUALAN_SUTANTO","root","");
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"Koneksi ke database gagal!","Pesan",JOptionPane.ERROR_MESSAGE,new
        ImageIcon("src/gambar/warn.png"));
        }
        }
    }
        
        private void setTabel1(){
        tabel1 = new DefaultTableModel();
        table_sutantodwiputra.setModel(tabel1);
        tabel1.addColumn("ID Transaksi");
        tabel1.addColumn("Kode Barang");
        tabel1.addColumn("Nama Barang");
        tabel1.addColumn("Harga");
        tabel1.addColumn("Jumlah Beli");
        tabel1.addColumn("Jumlah Bayar");
        tabel1.addColumn("Diskon");
        tabel1.addColumn("Total bayar");
    }
    
    private void tampil_data1(){
        tabel1.getDataVector().removeAllElements();
        tabel1.fireTableDataChanged();
        try {
        String query = "SELECT * FROM DATA_PENJUALAN ORDER BY id_transaksi DESC";
        ps = c.prepareStatement(query);
        r = ps.executeQuery();
        while (r.next()) {
        Object obj[] = new Object[9];
        obj[0] = r.getString(1);
        obj[1] = r.getString(2);
        obj[2] = r.getString(3);
        obj[3] = r.getString(4);
        obj[4] = r.getString(5);
        obj[5] = r.getString(6);
        obj[6] = r.getString(7);
        obj[7] = r.getString(8);
        tabel1.addRow(obj);
        }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        KdBrg_sutantodwiputra = new javax.swing.JComboBox<>();
        NamaBrg_sutantodwiputra = new javax.swing.JTextField();
        HargaBrg_sutantodwiputra = new javax.swing.JTextField();
        JmlBeli_sutantodwiputra = new javax.swing.JTextField();
        JmlBayar_sutantodwiputra = new javax.swing.JTextField();
        Diskon_sutantodwiputra = new javax.swing.JTextField();
        TotalByr_sutantodwiputra = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnBaru_sutantodwiputra = new javax.swing.JButton();
        btnHapus_sutantodwiputra = new javax.swing.JButton();
        btnSimpan_sutantodwiputra = new javax.swing.JButton();
        btnKeluar_sutantodwiputra = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_sutantodwiputra = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        IdTrs_sutantodwiputra = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BtnHitung_sutantodwiputra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Kode Barang");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Nama Barang");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah Beli");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah Bayar");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Diskon");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Total Bayar");

        KdBrg_sutantodwiputra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Barang", "001", "002" }));
        KdBrg_sutantodwiputra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KdBrg_sutantodwiputraActionPerformed(evt);
            }
        });

        NamaBrg_sutantodwiputra.setText("jTextField1");

        HargaBrg_sutantodwiputra.setText("jTextField2");

        JmlBeli_sutantodwiputra.setText("jTextField3");
        JmlBeli_sutantodwiputra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmlBeli_sutantodwiputraActionPerformed(evt);
            }
        });

        JmlBayar_sutantodwiputra.setText("jTextField4");

        Diskon_sutantodwiputra.setText("jTextField5");

        TotalByr_sutantodwiputra.setText("jTextField6");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnBaru_sutantodwiputra.setText("Data Baru");
        btnBaru_sutantodwiputra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaru_sutantodwiputraActionPerformed(evt);
            }
        });

        btnHapus_sutantodwiputra.setText("Hapus");
        btnHapus_sutantodwiputra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus_sutantodwiputraActionPerformed(evt);
            }
        });

        btnSimpan_sutantodwiputra.setText("Simpan");
        btnSimpan_sutantodwiputra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan_sutantodwiputraActionPerformed(evt);
            }
        });

        btnKeluar_sutantodwiputra.setText("Keluar");
        btnKeluar_sutantodwiputra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluar_sutantodwiputraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBaru_sutantodwiputra, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnHapus_sutantodwiputra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan_sutantodwiputra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar_sutantodwiputra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnBaru_sutantodwiputra)
                .addGap(18, 18, 18)
                .addComponent(btnHapus_sutantodwiputra)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan_sutantodwiputra)
                .addGap(18, 18, 18)
                .addComponent(btnKeluar_sutantodwiputra)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText("Aplikasi Penjualan Barang");

        table_sutantodwiputra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode_Barang", "Nama_Barang", "Harga", "Jumlah_Beli", "Jumlah_Bayar", "Diskon", "Total Bayar"
            }
        ));
        table_sutantodwiputra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_sutantodwiputraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_sutantodwiputra);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("ID Transaksi");

        IdTrs_sutantodwiputra.setText("jTextField0");
        IdTrs_sutantodwiputra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTrs_sutantodwiputraActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel10.setText("Sutanto Dwi Putra");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("22110233 - L2022");

        BtnHitung_sutantodwiputra.setText("Hitung");
        BtnHitung_sutantodwiputra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHitung_sutantodwiputraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KdBrg_sutantodwiputra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NamaBrg_sutantodwiputra)
                            .addComponent(HargaBrg_sutantodwiputra)
                            .addComponent(JmlBayar_sutantodwiputra)
                            .addComponent(Diskon_sutantodwiputra)
                            .addComponent(TotalByr_sutantodwiputra)
                            .addComponent(IdTrs_sutantodwiputra)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JmlBeli_sutantodwiputra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnHitung_sutantodwiputra)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(IdTrs_sutantodwiputra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(KdBrg_sutantodwiputra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NamaBrg_sutantodwiputra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(HargaBrg_sutantodwiputra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JmlBeli_sutantodwiputra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnHitung_sutantodwiputra))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JmlBayar_sutantodwiputra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Diskon_sutantodwiputra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TotalByr_sutantodwiputra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KdBrg_sutantodwiputraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KdBrg_sutantodwiputraActionPerformed
        // TODO add your handling code here:
        String selectedValue = KdBrg_sutantodwiputra.getSelectedItem().toString();
        if(selectedValue == "Kode Barang"){
            NamaBrg_sutantodwiputra.setText("");
            HargaBrg_sutantodwiputra.setText("");
        }else if(selectedValue == "001"){
            NamaBrg_sutantodwiputra.setText("Keyboard");
            HargaBrg_sutantodwiputra.setText("35000");
            Integer harga = Integer.parseInt(HargaBrg_sutantodwiputra.getText());
            HargaBrg_sutantodwiputra.setText(Integer.toString(harga));
        }else if(selectedValue == "002"){
            NamaBrg_sutantodwiputra.setText("Mouse");
            HargaBrg_sutantodwiputra.setText("25000");
            Integer harga = Integer.parseInt(HargaBrg_sutantodwiputra.getText());
            HargaBrg_sutantodwiputra.setText(Integer.toString(harga));
    }//GEN-LAST:event_KdBrg_sutantodwiputraActionPerformed
    }
    private void btnBaru_sutantodwiputraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaru_sutantodwiputraActionPerformed
        // TODO add your handling code here:
        String kodeRandom = generateRandomCode();
        String transactionId = "TRS0" + kodeRandom;
        IdTrs_sutantodwiputra.setText(transactionId);
        KdBrg_sutantodwiputra.setSelectedItem("");
        NamaBrg_sutantodwiputra.setText("");
        HargaBrg_sutantodwiputra.setText("");
        JmlBeli_sutantodwiputra.setText("");
        JmlBayar_sutantodwiputra.setText("");
        Diskon_sutantodwiputra.setText("");
        TotalByr_sutantodwiputra.setText("");
    }//GEN-LAST:event_btnBaru_sutantodwiputraActionPerformed

    private void btnHapus_sutantodwiputraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus_sutantodwiputraActionPerformed
        // TODO add your handling code here:
        try {
        String query = "DELETE FROM DATA_PENJUALAN WHERE id_transaksi='" + IdTrs_sutantodwiputra.getText() + "' ";
        ps = c.prepareStatement(query);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Telah Dihapus!");
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data Gagal Dihapus!");
        }
        tampil_data1();
    }//GEN-LAST:event_btnHapus_sutantodwiputraActionPerformed

    private void JmlBeli_sutantodwiputraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmlBeli_sutantodwiputraActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JmlBeli_sutantodwiputraActionPerformed

    private void IdTrs_sutantodwiputraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTrs_sutantodwiputraActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_IdTrs_sutantodwiputraActionPerformed

    private void table_sutantodwiputraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_sutantodwiputraMouseClicked
        int a = table_sutantodwiputra.getSelectedRow();
             if(a == -1){
             return;
             }
             String a1 = (String) table_sutantodwiputra.getValueAt(a, 0);
             String a2 = (String) table_sutantodwiputra.getValueAt(a, 1);
             String a3 = (String) table_sutantodwiputra.getValueAt(a, 2);
             String a4 = (String) table_sutantodwiputra.getValueAt(a, 3);
             String a5 = (String) table_sutantodwiputra.getValueAt(a, 4);
             String a6 = (String) table_sutantodwiputra.getValueAt(a, 5);
             String a7 = (String) table_sutantodwiputra.getValueAt(a, 6);
             String a8 = (String) table_sutantodwiputra.getValueAt(a, 7);
             IdTrs_sutantodwiputra.setText(a1);
             KdBrg_sutantodwiputra.setSelectedItem(a2);
             NamaBrg_sutantodwiputra.setText(a3);
             HargaBrg_sutantodwiputra.setText(a4);
             JmlBeli_sutantodwiputra.setText(a5);
             JmlBayar_sutantodwiputra.setText(a6);
             Diskon_sutantodwiputra.setText(a7);
             TotalByr_sutantodwiputra.setText(a8);
    }//GEN-LAST:event_table_sutantodwiputraMouseClicked

    private void btnKeluar_sutantodwiputraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluar_sutantodwiputraActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluar_sutantodwiputraActionPerformed

    private void btnSimpan_sutantodwiputraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan_sutantodwiputraActionPerformed
        // TODO add your handling code here:
        try {
        String query3 = "INSERT INTO DATA_PENJUALAN VALUES(?,?,?,?,?,?,?,?)";
        ps = c.prepareStatement(query3);
        ps.setString(1, IdTrs_sutantodwiputra.getText());
        ps.setString(2, (String) KdBrg_sutantodwiputra.getSelectedItem());
        ps.setString(3, NamaBrg_sutantodwiputra.getText());
        ps.setString(4, HargaBrg_sutantodwiputra.getText());
        ps.setString(5, JmlBeli_sutantodwiputra.getText());
        ps.setString(6, JmlBayar_sutantodwiputra.getText());
        ps.setString(7, Diskon_sutantodwiputra.getText());
        ps.setString(8, TotalByr_sutantodwiputra.getText());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data telah disimpan!");
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
        }
        tampil_data1();
    }//GEN-LAST:event_btnSimpan_sutantodwiputraActionPerformed

    private void BtnHitung_sutantodwiputraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHitung_sutantodwiputraActionPerformed
        // TODO add your handling code here:
                Double JumlahBayar = (Double.parseDouble(HargaBrg_sutantodwiputra.getText()))*(Double.parseDouble(JmlBeli_sutantodwiputra.getText()));
        JmlBayar_sutantodwiputra.setText(Double.toString(JumlahBayar));
        
        if(JumlahBayar >= 200000){
            Double DiskonHarga = (Double.parseDouble(JmlBayar_sutantodwiputra.getText()))* 0.3;
            Diskon_sutantodwiputra.setText(Double.toString(DiskonHarga));      
        }
        else if(JumlahBayar >= 100000){
            Double DiskonHarga = (Double.parseDouble(JmlBayar_sutantodwiputra.getText()))* 0.2;
            Diskon_sutantodwiputra.setText(Double.toString(DiskonHarga));
        }
        else if(JumlahBayar <= 100000){
            Diskon_sutantodwiputra.setText("0");
        }
        
        Double TotalBayar = (Double.parseDouble(JmlBayar_sutantodwiputra.getText()))-(Double.parseDouble(Diskon_sutantodwiputra.getText()));
        TotalByr_sutantodwiputra.setText(Double.toString(TotalBayar));
    }//GEN-LAST:event_BtnHitung_sutantodwiputraActionPerformed
    
    private String generateRandomCode() {

        UUID uuid = UUID.randomUUID();
        return uuid.toString().substring(0, 6); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan_sutantodwiputra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan_sutantodwiputra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan_sutantodwiputra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan_sutantodwiputra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan_sutantodwiputra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHitung_sutantodwiputra;
    private javax.swing.JTextField Diskon_sutantodwiputra;
    private javax.swing.JTextField HargaBrg_sutantodwiputra;
    private javax.swing.JTextField IdTrs_sutantodwiputra;
    private javax.swing.JTextField JmlBayar_sutantodwiputra;
    private javax.swing.JTextField JmlBeli_sutantodwiputra;
    private javax.swing.JComboBox<String> KdBrg_sutantodwiputra;
    private javax.swing.JTextField NamaBrg_sutantodwiputra;
    private javax.swing.JTextField TotalByr_sutantodwiputra;
    private javax.swing.JButton btnBaru_sutantodwiputra;
    private javax.swing.JButton btnHapus_sutantodwiputra;
    private javax.swing.JButton btnKeluar_sutantodwiputra;
    private javax.swing.JButton btnSimpan_sutantodwiputra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_sutantodwiputra;
    // End of variables declaration//GEN-END:variables
}
